/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.babbler.ws.io.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Avro schema used for representing a babble on Kafka */
@org.apache.avro.specific.AvroGenerated
public class BabbleKey2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6774878246405251364L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BabbleKey2\",\"namespace\":\"com.babbler.ws.io.avro.model\",\"doc\":\"Avro schema used for representing a babble on Kafka\",\"fields\":[{\"name\":\"keyword\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"keyword that identify the partition for the babble\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BabbleKey2> ENCODER =
      new BinaryMessageEncoder<BabbleKey2>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BabbleKey2> DECODER =
      new BinaryMessageDecoder<BabbleKey2>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<BabbleKey2> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<BabbleKey2> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BabbleKey2>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this BabbleKey2 to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a BabbleKey2 from a ByteBuffer. */
  public static BabbleKey2 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** keyword that identify the partition for the babble */
   private java.lang.String keyword;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BabbleKey2() {}

  /**
   * All-args constructor.
   * @param keyword keyword that identify the partition for the babble
   */
  public BabbleKey2(java.lang.String keyword) {
    this.keyword = keyword;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return keyword;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: keyword = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'keyword' field.
   * @return keyword that identify the partition for the babble
   */
  public java.lang.String getKeyword() {
    return keyword;
  }


  /**
   * Creates a new BabbleKey2 RecordBuilder.
   * @return A new BabbleKey2 RecordBuilder
   */
  public static com.babbler.ws.io.avro.model.BabbleKey2.Builder newBuilder() {
    return new com.babbler.ws.io.avro.model.BabbleKey2.Builder();
  }

  /**
   * Creates a new BabbleKey2 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BabbleKey2 RecordBuilder
   */
  public static com.babbler.ws.io.avro.model.BabbleKey2.Builder newBuilder(com.babbler.ws.io.avro.model.BabbleKey2.Builder other) {
    return new com.babbler.ws.io.avro.model.BabbleKey2.Builder(other);
  }

  /**
   * Creates a new BabbleKey2 RecordBuilder by copying an existing BabbleKey2 instance.
   * @param other The existing instance to copy.
   * @return A new BabbleKey2 RecordBuilder
   */
  public static com.babbler.ws.io.avro.model.BabbleKey2.Builder newBuilder(com.babbler.ws.io.avro.model.BabbleKey2 other) {
    return new com.babbler.ws.io.avro.model.BabbleKey2.Builder(other);
  }

  /**
   * RecordBuilder for BabbleKey2 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BabbleKey2>
    implements org.apache.avro.data.RecordBuilder<BabbleKey2> {

    /** keyword that identify the partition for the babble */
    private java.lang.String keyword;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.babbler.ws.io.avro.model.BabbleKey2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.keyword)) {
        this.keyword = data().deepCopy(fields()[0].schema(), other.keyword);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BabbleKey2 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.babbler.ws.io.avro.model.BabbleKey2 other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.keyword)) {
        this.keyword = data().deepCopy(fields()[0].schema(), other.keyword);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'keyword' field.
      * keyword that identify the partition for the babble
      * @return The value.
      */
    public java.lang.String getKeyword() {
      return keyword;
    }

    /**
      * Sets the value of the 'keyword' field.
      * keyword that identify the partition for the babble
      * @param value The value of 'keyword'.
      * @return This builder.
      */
    public com.babbler.ws.io.avro.model.BabbleKey2.Builder setKeyword(java.lang.String value) {
      validate(fields()[0], value);
      this.keyword = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'keyword' field has been set.
      * keyword that identify the partition for the babble
      * @return True if the 'keyword' field has been set, false otherwise.
      */
    public boolean hasKeyword() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'keyword' field.
      * keyword that identify the partition for the babble
      * @return This builder.
      */
    public com.babbler.ws.io.avro.model.BabbleKey2.Builder clearKeyword() {
      keyword = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BabbleKey2 build() {
      try {
        BabbleKey2 record = new BabbleKey2();
        record.keyword = fieldSetFlags()[0] ? this.keyword : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BabbleKey2>
    WRITER$ = (org.apache.avro.io.DatumWriter<BabbleKey2>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BabbleKey2>
    READER$ = (org.apache.avro.io.DatumReader<BabbleKey2>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
